// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200821191908_Pagination")]
    partial class Pagination
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Story");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 4,
                            Gender = "Male",
                            Name = "Flash",
                            Story = "Little bit of a scaredy cat, but will be a lover once he knows you."
                        },
                        new
                        {
                            CatId = 2,
                            Age = 6,
                            Gender = "Male",
                            Name = "Jazz",
                            Story = "Biggest cuddler and sweetest boy."
                        },
                        new
                        {
                            CatId = 3,
                            Age = 1,
                            Gender = "Female",
                            Name = "Raisin",
                            Story = "Will follow you wherever you go."
                        },
                        new
                        {
                            CatId = 4,
                            Age = 2,
                            Gender = "Female",
                            Name = "Maya",
                            Story = "Knows what she wants and how to manipulate you to get it."
                        },
                        new
                        {
                            CatId = 5,
                            Age = 7,
                            Gender = "Female",
                            Name = "Shiva",
                            Story = "She has always been that small and always will be."
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Story");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 2,
                            Gender = "Male",
                            Name = "Baloo",
                            Story = "Born with no hip sockets, had them installed by doctors later. Will love you forever."
                        },
                        new
                        {
                            DogId = 2,
                            Age = 3,
                            Gender = "Female",
                            Name = "Hambone",
                            Story = "Always wants to run in the park."
                        },
                        new
                        {
                            DogId = 3,
                            Age = 5,
                            Gender = "Male",
                            Name = "Ziggy",
                            Story = "Give him treats and take him for walks and he is yours."
                        },
                        new
                        {
                            DogId = 4,
                            Age = 2,
                            Gender = "Female",
                            Name = "Duchess",
                            Story = "Wants to sits in your lap and burrow under the covers to keep your feet warm."
                        },
                        new
                        {
                            DogId = 5,
                            Age = 1,
                            Gender = "Male",
                            Name = "Bowser",
                            Story = "Super active and playful, wants a family that spends most of their time outside."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
